### ISSUE TITLE
How to remove cache for specific image url after image was loaded?

### ISSUE THREAD

**Issue by luatnd** [crelies/RemoteImage#16]
As I can see in the source code, RemoteImage cache supported to remove cache by key:
```
RemoteImageService.cache.removeObject(forKey: url)
```

But I don't know how to clear cache immediately after the image was loaded, 
How can I do that?

**Comment by crelies** [comment]
Hey,

I just published version `4.0.0`. You could accomplish it by implementing a custom `RemoteImageService`.
