### ISSUE TITLE
Doesn't load the image when in a Button

### ISSUE THREAD

**Issue by tpritc** [crelies/RemoteImage#2]
<img width="1451" alt="Screen Shot 2019-09-23 at 3 43 26 PM" src="https://user-images.githubusercontent.com/1939143/65435755-edb2a500-de18-11e9-8acb-aec4a5f0e861.png">

I've got an image in a button I'm trying to present to my users (their avatar). I want it to be in a button (specifically the navigation bar items, like in the App Store, but this bug applies to all buttons), but the image doesn't seem to load while in a button. It works absolutely as-expected when outside of a button.

Any ideas? I'm still pretty new to SwiftUI, and I can't seem to work it out.

**Comment by crelies** [comment]
Hey @tpritc ,

try adding the modifier `.renderingMode(.original)` to the image in the `imageView` block. Then it should work like a charm ;)

**Comment by tpritc** [comment]
Perfect, that's done it, thank you!
