### ISSUE TITLE
Would you consider an open source license for the package?

### ISSUE THREAD

**Issue by chrissearle** [crelies/RemoteImage#4]
I'm working on an app for the norwegian java user group. It has so far 4 dependencies via swift package manager - 3 have MIT license and RemoteImage I can't see what licence if any applies.

Wondering if you'd consider adding an open source license? Personal preference for me (as it would fit with both the other dependencies and also with other things we do in the group) would be [MIT](https://opensource.org/licenses/MIT) - but of course that would be your choice :)

**Comment by crelies** [comment]
Hey @chrissearle ,

thanks for reaching out. To be honest I just forgot to add the MIT license ;)

It's added now. Enjoy 🚀
