### ISSUE TITLE
Termination due to memory usage issue

### ISSUE THREAD

**Issue by homanp** [crelies/RemoteImage#8]
Hey there! 

Using RemoteImage in a project of mine in which I'm using the `List` view and RemoteImage together and getting `Message from debugger: Terminated due to memory issue`. 

Do you have any suggestion on how to mitigate this issue?

Thanks!

**Comment by crelies** [comment]
Hey @homanp ,

sorry for the delay. I'm very busy at the moment. Please check out the latest release (**2.0.2**). I hope that bugfix release resolves your issue.

Best regards
Chris

**Comment by homanp** [comment]
Thanks!
